// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS0BhxyQPqIbcPdAybxinaoxLFFWi5634',
    appId: '1:1066335156023:web:50dffbf532cf1a8e2f0cb2',
    messagingSenderId: '1066335156023',
    projectId: 'authtutorial-5ce19',
    authDomain: 'authtutorial-5ce19.firebaseapp.com',
    storageBucket: 'authtutorial-5ce19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClcvortVho1sl_MAxhYoiL7oOWRFeIbF4',
    appId: '1:1066335156023:android:43a5f3f9064b75182f0cb2',
    messagingSenderId: '1066335156023',
    projectId: 'authtutorial-5ce19',
    storageBucket: 'authtutorial-5ce19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC72UJLHRvMPoD7cgcAB2I0R3_TABHQ9ZY',
    appId: '1:1066335156023:ios:5af5afdd9ed988ce2f0cb2',
    messagingSenderId: '1066335156023',
    projectId: 'authtutorial-5ce19',
    storageBucket: 'authtutorial-5ce19.firebasestorage.app',
    iosBundleId: 'com.myapp.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC72UJLHRvMPoD7cgcAB2I0R3_TABHQ9ZY',
    appId: '1:1066335156023:ios:5af5afdd9ed988ce2f0cb2',
    messagingSenderId: '1066335156023',
    projectId: 'authtutorial-5ce19',
    storageBucket: 'authtutorial-5ce19.firebasestorage.app',
    iosBundleId: 'com.myapp.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS0BhxyQPqIbcPdAybxinaoxLFFWi5634',
    appId: '1:1066335156023:web:079b23cec69c2d4f2f0cb2',
    messagingSenderId: '1066335156023',
    projectId: 'authtutorial-5ce19',
    authDomain: 'authtutorial-5ce19.firebaseapp.com',
    storageBucket: 'authtutorial-5ce19.firebasestorage.app',
  );
}
